name: Continuous VPS (Auto-Restart, 5h30m, Persistent Data)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/330 * * * *'  # Every 330 minutes (5h30m)

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Data
        uses: actions/download-artifact@v4
        with:
          name: vps-data
          path: /root/mydata
        continue-on-error: true

      - name: Start SSHX VPS
        run: |
          mkdir -p /root/mydata
          cd /root/mydata
          curl -sSf https://sshx.io/get | sh -s run &
          sleep 5
          echo "VPS ready. Data folder: /root/mydata"
          tail -f /dev/null &  # Keeps alive until timeout
          PID=$!
          sleep $((330*60 - 120))  # Stop 2 mins before timeout to save data
          kill $PID

      - name: Save Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vps-data
          path: /root/mydata

      - name: Trigger Next Run
        if: always()
        run: |
          echo "Triggering next run..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
            -d '{"ref":"main"}'
