name: noVNC with LocalXpose
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install & Start noVNC with LocalXpose
        run: sudo apt update && sudo apt install -y xfce4 xfce4-goodies novnc websockify x11vnc && mkdir -p ~/.vnc && x11vnc -storepasswd 1234 ~/.vnc/passwd && websockify --web=/usr/share/novnc/ 6080 localhost:5900 & wget -qO- https://localxpose.io/api/releases/stable/linux64.zip | bsdtar -xvf- && chmod +x loclx && ./loclx tunnel http --to localhost:6080 --token $LOCALXPOSE_TOKEN
        env:
          LOCALXPOSE_TOKEN: ${{ secrets.LOCALXPOSE_TOKEN }}
