name: noVNC Desktop with LocalXpose

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Restart every 6 hours for persistence

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 330 # 5h30m

    steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies novnc websockify x11vnc wget curl unzip

    - name: Set up VNC server
      run: |
        export DISPLAY=:1
        Xvfb :1 -screen 0 1024x768x16 &
        x11vnc -display :1 -nopw -forever -shared &
        websockify --web=/usr/share/novnc/ 6080 localhost:5900 &

    - name: Install LocalXpose
      run: |
        wget https://api.localxpose.io/api/releases/latest/download/localxpose-linux-x64.zip
        unzip localxpose-linux-x64.zip
        sudo mv loclx /usr/local/bin/loclx
        loclx authtoken ${{ secrets.LOCALXPOSE_TOKEN }}

    - name: Start tunnel
      run: |
        loclx tunnel http --to :6080
